version: "3.9"
services:
  web:
    image: isadora145/lista-de-tarefas-docker:v1
    container_name: web_lt
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        PHP_VERSION: '8.2.4-fpm-bullseye'
    environment:
      - APP_ENV=local
    volumes:
      - ./app:/var/www/app
    ports:
      - "8080:80" #http
    